run_tests:
  stage: test
  image: python:3.7
  script:
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - --version 1.0.10 && /root/.poetry/bin/poetry config virtualenvs.create false
    - $HOME/.poetry/bin/poetry install --no-interaction
    - python -m readme_renderer README.rst >/dev/null
    - flake8 --ignore=W504,W601 cacheflow
    - cacheflow run examples/pipeline.yaml
    - cacheflow run examples/pipeline.yaml
    - noteflow examples/notebook.cfnb
    - noteflow examples/notebook.cfnb
    - python tests
    - apt-get update && apt-get install -y nodejs yarnpkg
    - rm ui/yarn.lock
    - (cd ui && yarnpkg install)
    - (cd ui && yarnpkg run check)
    - (cd ui && yarnpkg build)
    - mkdir cacheflow/web/ui cacheflow/web/ui/static
    - mv ui/build/index.html cacheflow/web/ui/
    - mv ui/build/* cacheflow/web/ui/static/
